services:
  ollama:
    image: ollama/ollama:0.9.0
    ports:
      - 11434:11434
    volumes: 
      - ./prod/ollama:/root/.ollama
    container_name: ollama    
    mem_limit: 4g
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker

  # 向量資料庫
  # 管理介面：http://localhost:6333/dashboard
  qdrant:
    image: qdrant/qdrant:v1.14.1
    ports:
      - 6333:6333
      - 6334:6334
    volumes: 
      - ./prod/ollama:/root/.ollama
    container_name: qdrant     
    networks:
      - ollama-docker

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:v0.6.13
    container_name: ollama-webui
    volumes:
      - ./prod/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8888:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:11434 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=Lawrence AI
      - WEBUI_URL=http://localhost:8888
      - WEBUI_SECRET_KEY=t0p-lawrence
    extra_hosts:
      - host.docker.internal:host-gateway
    # restart: unless-stopped
    restart: always
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false